# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: D

on:
  push:
    branches: [ "vardec_varass_dependency" ]
  pull_request:
    branches: [ "vardec_varass_dependency" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest]
        dc: [dmd-2.101.0]
        exclude:
          - { os: macOS-latest, dc: dmd-2.085.0 }

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      
      
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Build
        run: dub build
        
      
        
      - uses: actions/upload-artifact@v3
        with:
          name: tbin
          path: tlang
          
  test:
    needs: build
    name: Run compiler tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download math result for job 1
        uses: actions/download-artifact@v3
        with:
          name: tbin
        
      - name: Chmod compiler
        run: chmod +x tlang
        
        
      - name: Simple function call
        run: ./tlang typecheck source/tlang/testing/typecheck/simple_function_call.t
      - name: Simple function call 1
        run: ./tlang typecheck source/tlang/testing/typecheck/simple_function_call_1.t
      - name: Simple float constant
        run: ./tlang typecheck source/tlang/testing/typecheck/simple_float_constant.t
      - name: Simple float constant bad
        run: ./tlang typecheck source/tlang/testing/typecheck/simple_float_constant_bad.t
      - name: Simple string
        run: ./tlang typecheck source/tlang/testing/typecheck/simple_string.t
      - name: Simple array
        run: ./tlang typecheck source/tlang/testing/typecheck/simple_array.t
      - name: Collide container module1
        run: ./tlang typecheck source/tlang/testing/collide_container_module1.t
      - name: Collide container module2
        run: ./tlang typecheck source/tlang/testing/collide_container_module2.t
        
      
      
