# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
name: D

on:
  push:
    branches: [ "vardec_varass_dependency" ]
  pull_request:
    branches: [ "vardec_varass_dependency" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
        dc: [dmd-2.101.0]
        exclude:
          - { os: macOS-latest, dc: dmd-2.085.0 }

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/upload-artifact@v3
        with:
          name: tbin
          path: tlang
      
      - name: Install D compiler
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.dc }}

      - name: Build
        run: dub build
        
